---
name: Publish database
on:
  workflow_dispatch:
  push:
    tags:
      - v**
jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make database
        run: |-
          make centreline.db.gz
          make SHA256SUMS
      - name: Publish database
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: centreline.db.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Publish checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: SHA256SUMS
          tag: ${{ github.ref }}
          overwrite: true
